name: Build Xamarin.Android demo app

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: nuget restore Xamarin.Plugin.Firebase.sln

    - name: Build
      run: msbuild Demo/Demo.Android/Demo.Droid.csproj /t:PackageForAndroid /p:Configuration=Debug