name: Build Xamarin.Android demo app

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Decode google-services.json
      env:
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON > Demo/Demo.Android/Assets/google-services.json

    - name: Install dependencies
      run: nuget restore Xamarin.Plugin.Firebase.sln

    - name: Build
      run: msbuild Demo/Demo.Android/Demo.Droid.csproj /t:PackageForAndroid /p:Configuration=Debug