name: Build

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Install .NET MAUI
      run: dotnet workload install maui

    - name: Install dependencies
      run: nuget restore Xamarin.Plugin.Firebase.sln

    - name: Build
      run: dotnet build Demo/Demo.Maui/Demo.Maui.csproj -c Release -f net6.0-android
